# This SPARQL adds schema:url to events.

PREFIX schema: <http://schema.org/>

INSERT {
  ?event_node schema:url <subject_url> .
}
WHERE {
  {
    SELECT DISTINCT ?event_node
    WHERE {
      ?event_node a schema:Event .
      FILTER NOT EXISTS { ?event_node schema:url ?some_object }
    }
  }
  ?event_node ?p ?o
}