# This SPARQL adds schema:url to events that do not already have a schema:url.
# It only targets resources of type schema:Event.

PREFIX schema: <http://schema.org/>

INSERT {
  ?event_node schema:url <subject_url> .
}
WHERE {
  ?event_node a schema:Event .
  FILTER NOT EXISTS { ?event_node schema:url ?some_object }
}
 
