PREFIX schema: <http://schema.org/>

delete {
    ?entity schema:contactPoint ?contactPoint .
}
insert {
    ?entity schema:contactPoint ?prime_contactPoint .
}
where {
    ?entity a schema:Organization ;
            schema:contactPoint ?contactPoint .
    filter (isBLANK(?contactPoint)) 
    filter(!isBLANK(?entity))
    
    # select a random blank node to use as prime
    {
        select ?entity (sample(?contactPoint) as ?prime_contactPoint)
        where {
            ?entity a schema:Organization ;
                    schema:contactPoint ?contactPoint .
            filter (isBLANK(?contactPoint)) 
            filter(!isBLANK(?entity))
        }
        group by ?entity
    }
}
