PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE {
  ?entity schema:contactPoint ?contactPoint .
}
INSERT {
  ?entity schema:contactPoint ?prime_contactPoint .
}
WHERE {
  {
    SELECT ?entity (SAMPLE(?contactPoint) AS ?prime_contactPoint)
    WHERE {
      ?entity a schema:Organization ;
              schema:contactPoint ?contactPoint .
      FILTER(isBlank(?contactPoint))
      FILTER(!isBlank(?entity))
    }
    GROUP BY ?entity
  }

  # only delete the other blank contactPoints
  ?entity schema:contactPoint ?contactPoint .
  FILTER(isBlank(?contactPoint))
  FILTER(?contactPoint != ?prime_contactPoint)
}
