PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?event) AS ?count)
WHERE {
  VALUES ?class { 
    schema:Event 
    schema:TheaterEvent 
    schema:MusicEvent 
    schema:Festival 
  }
  ?event rdf:type ?class .
}

