PREFIX schema: <http://schema.org/>
DELETE {
    ?e schema:sameAs ?sameAs .
}
INSERT {
    ?e schema:sameAs ?fixedWikidataURI .
}
WHERE {
    ?e schema:sameAs ?sameAs .
    FILTER(STRSTARTS(STR(?sameAs), "http://www.wikidata.org/wiki/Q"))
    BIND(
        IRI(REPLACE(
            STR(?sameAs),
            "http://www.wikidata.org/wiki/",
            "http://www.wikidata.org/entity/"
        )) AS ?fixedWikidataURI
    )
  }
