# URIs can be mistakenly HTML encoded
# '&' has HTML code:
# - Name code: '&amp;' 
# - Decimal code: '&#038;' or '&#38;'
# - Hex code: '&#x26;'

DELETE {
  ?subject <http://schema.org/url> ?oldUrl .
}
INSERT {
  ?subject <http://schema.org/url> ?newUrl .
}
WHERE {
  ?subject <http://schema.org/url> ?oldUrl .
  
  FILTER(CONTAINS(STR(?oldUrl), "#038;"))
  BIND(IRI(REPLACE(STR(?oldUrl), "#038;", "")) AS ?newUrl)
}
