PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE {
  ?address schema:addressCountry ?country .
  ?country ?p ?o .
}
INSERT {
  ?address schema:addressCountry ?countryName .
}
WHERE {
  ?address rdf:type schema:PostalAddress ;
           schema:addressCountry ?country .
  
  ?country rdf:type schema:Country ;
           schema:name ?countryName ;
           ?p ?o .
}
