PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE {
  ?s rdf:type ?entityClass
}
INSERT {
  ?s rdf:type ?updatedEntityClass
}
WHERE {
  ?s rdf:type ?entityClass .
  FILTER(STRSTARTS(STR(?entityClass), STR(schema:)))
  FILTER(REGEX(SUBSTR(STRAFTER(STR(?entityClass), STR(schema:)), 1, 1), "^[a-z]"))
  BIND(URI(CONCAT(STR(schema:), UCASE(SUBSTR(STRAFTER(STR(?entityClass), STR(schema:)), 1, 1)) , SUBSTR(STRAFTER(STR(?entityClass), STR(schema:)), 2))) AS ?updatedEntityClass)
}
