PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (COUNT(?organization) AS ?count)
WHERE {
  VALUES ?class { 
    schema:Organization 
    schema:LocalBusiness 
    schema:PerformingGroup
  }
  ?organization rdf:type ?class .
}

