PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT (COUNT(?person) AS ?count)
WHERE {
  VALUES ?class { 
    schema:Person 
  }
  ?person rdf:type ?class .
}

