PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT (COUNT(?place) AS ?count)
WHERE {
  VALUES ?class { 
    schema:Place 
    schema:PerformingArtsTheater 
    schema:MusicVenue 
    schema:CivicStructure 
    schema:MovieTheater
  }
  ?place rdf:type ?class .
}

