PREFIX schema: <http://schema.org/>
PREFIX schemaHttps: <https://schema.org/>

DELETE {
  ?s ?p ?o .
}
WHERE {
  {
    ?s a ?type ;
       ?p ?o .
    VALUES ?type {
      schema:SiteNavigationElement
      schemaHttps:SiteNavigationElement
      schema:WPHeader
      schema:WPFooter
      schema:BreadcrumbList
      schema:ListItem
    }
  }
  UNION
  {
    ?s ?predicate ?role ;
      ?p ?o .
    VALUES ?predicate {
      <http://www.w3.org/1999/xhtml/vocab#role>
    }
  }
}
