name: 'Custom Artsdata Pipeline Action'
description: 'A custom action for the Artsdata pipeline'

inputs:
  artifact:
    description: 'Name of the artifact'
    required: true
  publisher:
    description: 'URI of the publisher'
    required: true
    secret: true
  downloadUrl:
    description: 'URL to download'
    required: true
  downloadFile:
    description: 'Name of the file to download with extension'
    required: false
  comment:
    description: 'Comment'
    required: false
  group:
    description: 'Group of artifacts/versions. Typically the name of the tool creating the artifact. Use unreserved characters.'
    required: false
  version:
    description: 'Version of the artifact. Usually a date. For example: 2020-10-23. Use unreserved characters.'
    required: false
  reportCallbackUrl:
    description: 'URL to send back the data validation report asynchronously using POST "Content-Type: application/json"'
    required: false
  shacl:
    description: 'URL to the SHACL file'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
