name: 'Custom Artsdata Pipeline Action'
description: 'A custom action for the Artsdata pipeline'

inputs:
  page-url:
    description: 'URL of the page to crawl'
    required: true
  entity-identifier:
    description: 'Identifier of the entity'
    required: true
  is-paginated:
    description: 'Whether the page is paginated'
    required: true
  headless:
    description: 'Whether to run in headless mode'
    required: true
  artifact:
    description: 'Name of the artifact'
    required: true
  publisher:
    description: 'URI of the publisher'
    required: false
    secret: true
  downloadFile:
    description: 'Name of the file to download with extension'
    required: true
  comment:
    description: 'Comment'
    required: false
  group:
    description: 'Group of artifacts/versions. Typically the name of the tool creating the artifact. Use unreserved characters.'
    required: false
  version:
    description: 'Version of the artifact. Usually a date. For example: 2020-10-23. Use unreserved characters.'
    required: false
  reportCallbackUrl:
    description: 'URL to send back the data validation report asynchronously using POST "Content-Type: application/json"'
    required: false
  shacl:
    description: 'URL to the SHACL file'
    required: false
  token:
    description: 'GitHub token'
    secret: true
    required: true

runs: 
  using: 'composite'
  steps:
    - name: Fetch Data using Docker
      run: |
        docker build -t rdf-fetcher .
        docker run -v $(pwd)/output:/usr/src/app/output rdf-fetcher \
          "${{ inputs.page-url }}" \
          "${{ inputs.entity-identifier }}" \
          "output/${{ inputs.downloadFile }}" \
          "${{ inputs.is-paginated }}" \
          "${{ inputs.headless }}"
      shell: bash

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add "output/${{ inputs.file_name }}"
        git commit -m "Add data generated by the script"
        git push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Push to Artsdata
      run: |

        artifact=${{ inputs.artifact }}
        publisher=${{ inputs.publisher }}
        downloadFile=${{ inputs.downloadFile }}
        repo=${{ github.repository }}
        ref=${{ github.ref }}
        group=${{ inputs.group }}
        version=${{ inputs.version }}
        comment=${{ inputs.comment }}

        downloadUrl="https://raw.githubusercontent.com/${repo}/${ref}/output/${downloadFile}"

        group=${group:-${repo#*/}}
        version=${version:-$(date +%Y-%m-%dT%H:%M:%S | sed 's/:/_/g')}
        comment=${comment:-"Published by ${group} on ${version}"}

        data=$(jq -n \
        --arg artifact "$artifact" \
        --arg publisher "$publisher" \
        --arg group "$group" \
        --arg version "$version" \
        --arg downloadUrl "$downloadUrl" \
        --arg downloadFile "$downloadFile" \
        --arg comment "$comment" \
        '{
          artifact: $artifact,
          publisher: $publisher,
          group: $group,
          version: $version,
          downloadUrl: $downloadUrl,
          downloadFile: $downloadFile,
          comment: $comment
        }'
        )

        echo "Data: $data"

        response=$(curl -s -w "%{http_code}" -o response.txt -X POST http://api.artsdata.ca/databus/ \
        -H "Content-Type: application/json" \
        -d "$data")

        if [[ "$response" -ne 200 ]]; then
        echo "Error: $(cat response.txt)"
        else
        echo "Success: Data posted successfully."
        fi
      shell: bash