name: 'Custom Artsdata Pipeline Action'
description: 'A custom action for the Artsdata pipeline'

inputs:
  artifact:
    description: 'Name of the artifact'
    required: true
  publisher:
    description: 'URI of the publisher'
    required: true
    secret: true
  downloadUrl:
    description: 'URL to download'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
