name: Custom crawl test

on:
  workflow_dispatch:
    inputs:
      page-url:
        description: 'URL of the page to crawl'
      entity-identifier:
        description: 'Identifier of the entity'
      is-paginated:
        description: 'Whether the page is paginated'
        default: 'false'
      headless:
        description: 'Whether to run in headless mode'
        required : false
        default: 'false'
      fetch-urls-headlessly:
        description: 'Set as true to fetch the entity URLs headlessly'
        default: 'false'
        required: false
      offset:
        description: 'Offset for paginated pages'
        default: '1'
        required: false
      custom-user-agent:
        description: 'Custom user agent string'
        required: false
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Timezone
        run: |
          sudo apt-get update
          sudo apt-get install -y tzdata
          echo "America/Toronto" | sudo tee /etc/timezone
          sudo ln -sf /usr/share/zoneinfo/America/Toronto /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate config.yml
        run: |
          mkdir -p output
          cat <<EOF > config.yml
          mode: "fetch"
          page_url: "${{ inputs.page-url }}"
          entity_identifier: "${{ inputs.entity-identifier }}"
          is_paginated: ${{ inputs.is-paginated }}
          headless: ${{ inputs.headless }}
          fetch_urls_headlessly: ${{ inputs.fetch-urls-headlessly }}
          offset: ${{ inputs.offset }}
          custom_user_agent: ${{
            inputs.custom-user-agent && format('"{0}"', inputs.custom-user-agent) || 'null'
          }}
          callback_url: null
          workflow_id: "${{ github.workflow }}"
          actor: "${{ github.actor }}"
          token: null
          repository: "${{ github.repository }}"
          artifact: "test-events"
          publisher: "test-publisher"
          downloadUrl: ""
          reference: "${{ github.ref_name }}"
          version: "1.0.0"
          comment: "Test comment"
          group: "test-group"
          download_file: "output/test-events2.jsonld"
          download_url: "https://example.com/test.jsonld"
          shacl: null
          EOF
      - name: Run Ruby script with config
        run: |
          bundle exec ruby src/main.rb config.yml   
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jsonld-data
          path: output/
    
