name: Test to check fetching, commiting and pushing files to Artsdata.

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          mode: 'fetch-push'
          page-url: 'https://capitol.nb.ca/en/tickets-events?start='
          entity-identifier: 'div.fc-item-block-standard-wrapper.odd a, div.fc-item-block-standard-wrapper.even a'
          downloadFile: "capitolnb-events.jsonld"
          artifact: capitol-nb-ca
          is-paginated: "0"
          headless: "true"
          offset: "12"
          publisher: ${{ secrets.PUBLISHER_URI_GREGORY }}
          token: ${{ secrets.DEV_PAT }}
