name: Test to check fetching, commiting and pushing files to Artsdata.

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          mode: 'fetch-push'
          page-url: 'https://www.aramusique.org/evenements/liste/page/1'
          entity-identifier: 'h3.tribe-events-calendar-list__event-title.tribe-common-h6.tribe-common-h4--min-medium a'
          downloadFile: "aramusique-test.jsonld"
          artifact: test-artifact
          publisher: ${{ secrets.PUBLISHER_URI_GREGORY }}
          token: ${{ secrets.DEV_PAT }}
