name: Push Culture Mauricie Organizations

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          artifact: culture-mauricie-cms-organizations
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: "https://footlight-cms-entities-exported.s3.ca-central-1.amazonaws.com/culture-mauricie-organizations.ttl?re[…]61513902f5c9f6aea57e9fe84b18d8bdf86b68"
          downloadFile: "culture-mauricie-organizations.ttl"
          group: "artsdata-planet-footlight"
