name: Push IPAA Entities

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          artifact: ipaa-entities
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: "https://raw.githubusercontent.com/culturecreates/artsdata-planet-ipaa/main/output/entities.jsonld"
          group: "artsdata-planet-ipaa"
