name: Push Culture Mauricie Organizations

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          artifact: culture-mauricie-cms-organizations
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: "https://drive.google.com/uc?export=download&id=1pFFYFcyFpB4SjehR0TCG1DF5jt7ULC84"
          downloadFile: "culture-mauricie-organizations.ttl"
          group: "artsdata-planet-footlight"
