name: Test to check pushing files to artsdata.

on:
  workflow_dispatch:
            
jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action setup
        uses: ./
        with:
          downloadUrl: "https://raw.githubusercontent.com/culturecreates/artsdata-pipeline-action/refs/heads/enhancement/issue-1/output/aramusique-test.jsonld"
          artifact: test-artifact
          publisher: ${{ secrets.PUBLISHER_URI_GREGORY }}
